version: '3'
services:
    rabbitmq:
        hostname: jsyfer_rabbitmq
        container_name: jsyfer-rabbitmq
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"