version: "3.9"

services:
  goodsmanager:
    image: goodsmanager:latest
    container_name: goodsmanager
    restart: always
    ports:
      - 8088:8088
    networks:
      hostnet: {}
networks:
 hostnet:
   external: true
   name: host